### ISSUE TITLE
Unable to run on multiple threads

### ISSUE THREAD

**Issue by gpiechnik2** [wosp-io/xk6-playwright#2]
Hi, it is impossible to run a script on multiple threads. Below I attach the interior of the script to reproduce and the error from the console. It appears after 3 seconds after running.

```
import pw from 'k6/x/playwright';


export const options = {
  duration: '10m', 
  vus: 3
};

export default function () {
  pw.launch()
  pw.newPage()
  pw.goto("https://k6.io/")

  //print out real user metrics of the google serach page
  console.log(`First Paint: ${pw.firstPaint()}ms`)
  console.log(`First Contentful Paint: ${pw.firstContentfulPaint()}ms`)
  console.log(`Time to Minimally Interactive: ${pw.timeToMinimallyInteractive()}ms`)
  console.log(`First Input Delay: ${pw.firstInputDelay()}ms`)

  pw.kill()
}
```

```
node:events:368                                                                                                                                               
      throw er; // Unhandled 'error' eventd 0 interrupted iterations                                                                                               
      ^   [--------------------------------------] 3 VUs  00m03.5s/10m0s

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Users\figaro\AppData\Local\ms-playwright-go\1.20.0-beta-1647057403000\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\figaro\AppData\Local\ms-playwright-go\1.20.0-beta-1647057403000\package\lib\cli\driver.js:67:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\figaro\AppData\Local\ms-playwright-go\1.20.0-beta-1647057403000\package\lib\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispose (C:\Users\figaro\AppData\Local\ms-playwright-go\1.20.0-beta-1647057403000\package\lib\dispatchers\dispatcher.js:124:41)   
    at CRBrowserContext.<anonymous> (C:\Users\figaro\AppData\Local\ms-playwright-go\1.20.0-beta-1647057403000\package\lib\dispatchers\browserContextDispatcher.js:80:12)
    at CRBrowserContext.emit (node:events:402:35)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4047,
  sys.\xk6-playwright.exe run .\script.js
```

**Comment by nicholasvuono** [comment]
Ah yes, so this is an intended feature.

We believe running a single browser is all that is necessary. Multiple instances on one system will compete for resources and could affect the performance metrics returned. 

Ideally the load would be driven via backend requests and a single browser instance can then determine what the end user experience is like.

In addition, pooling browser launches and dev tools protocol connections can be a bit challenging, and is outside of the original scope of this project.
